train: 
  seed: 200
  batch_size: 2
  num_workers: 0

data: 
  - dataset:
      name: lvidlandmark
      data_dir: 'data/LVID/LV_PLAX2_cleaned'
      metadata_dir: 'data/lv_plax2_cleaned_info_landmark_gt_filtered_short.csv'
      transform: 
        image_size: 224
        crop_size: 28

  - dataset:
      name: lvotlandmark
      data_dir: 'data/LVOT_cleaned'
      metadata_dir: 'data/LVOT_Cleaned_all_short.csv'
      heatmap_radius: 7
      transform: 
        image_size: 224
        crop_size: 28


